"use client";
import {FormEvent,useMemo,useState} from "react";
import {useQuery} from "@tanstack/react-query";
import {api} from "@/lib/api";
import Shell from "@/components/Shell";
type Project={id:string;name:string;client:string|null;description:string|null;daily_report:string|null;status:string;priority:"CRITICAL"|"HIGH"|"MEDIUM"|"LOW";start_date:string|null;deadline:string|null;progress:number;assigned_to:string|null;source:string;source_id:string|null;updated_at:string};
const stages=["التحليل","التصميم","البرمجة","الاختبار والمراجعة","التسليم","الدعم الفني"];
const colors:Record<string,string>={"التحليل":"#7667d8","التصميم":"#d46a98","البرمجة":"#247f75","الاختبار والمراجعة":"#d68a21","التسليم":"#3975bd","الدعم الفني":"#718076"};
function stageOf(s:string){const v=s.toLowerCase();if(v.includes("تحليل")||v.includes("analysis"))return stages[0];if(v.includes("تصميم")||v.includes("design"))return stages[1];if(v.includes("برمج")||v.includes("development")||v.includes("programming"))return stages[2];if(v.includes("تيست")||v.includes("اختبار")||v.includes("testing")||v.includes("review"))return stages[3];if(v.includes("تسليم")||v.includes("delivery"))return stages[4];return stages[5]}
const blank={name:"",client:"",description:"",daily_report:"",status:"التحليل",priority:"MEDIUM",start_date:"",deadline:"",progress:0,assigned_to:""};
export default function Dashboard(){const{data=[],isLoading,error,refetch}=useQuery({queryKey:["private-projects"],queryFn:()=>api<Project[]>("/projects")});const[q,setQ]=useState("");const[editing,setEditing]=useState<Project|null|"new">(null);const rows=useMemo(()=>data.filter(p=>(p.name+" "+(p.source_id||"")+" "+p.status+" "+(p.daily_report||"")).toLowerCase().includes(q.toLowerCase())),[data,q]);const urgent=rows.filter(p=>p.priority==="CRITICAL"||p.priority==="HIGH");const stable=rows.filter(p=>!urgent.includes(p));return <Shell><div dir="rtl"><header className="mb-7 rounded-[28px] bg-ink p-7 text-white"><p className="text-xs font-black tracking-[.18em] text-lime">مساحة نهال الخاصة · قابلة للتعديل</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-4xl font-black">لوحة متابعة مشاريعي</h1><p className="mt-2 text-white/65">عدّلي الحالة والتواريخ والتقرير اليومي مباشرة من كل مشروع.</p></div><button onClick={()=>setEditing("new")} className="rounded-xl bg-lime px-5 py-3 font-black text-ink">+ إضافة مشروع</button></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="إجمالي المشاريع" value={data.length}/><Metric label="أولوية ومتابعة" value={data.filter(p=>["CRITICAL","HIGH"].includes(p.priority)).length}/><Metric label="لها تقرير يومي" value={data.filter(p=>p.daily_report?.trim()).length}/></div></header><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black tracking-[.16em] text-rust">الأهم أولًا</p><h2 className="mt-1 text-3xl font-black">آخر الأولويات والمتابعة</h2></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحثي باسم المشروع أو الكود أو التقرير" className="w-full rounded-xl border border-ink/20 bg-white p-3 sm:w-96"/></div>{error&&<p className="card p-6 text-rust">تعذر تحميل المشاريع. افتحي ملف التشغيل وسجلي الدخول من جديد.</p>}{isLoading?<p className="card p-10 text-center text-sage">جاري تحميل بياناتك…</p>:<><StageGroups items={urgent} edit={setEditing}/><div className="mb-5 mt-14 border-t-2 border-ink/10 pt-8"><p className="text-xs font-black tracking-[.16em] text-sage">المتابعة الدورية</p><h2 className="mt-1 text-3xl font-black">المشاريع المستقرة حسب المرحلة</h2></div><StageGroups items={stable} edit={setEditing}/></>}{editing&&<Editor project={editing==="new"?null:editing} close={()=>setEditing(null)} saved={()=>{setEditing(null);refetch()}}/>}</div></Shell>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/15 bg-white/5 p-4"><small className="text-white/60">{label}</small><b className="mt-1 block text-3xl">{value}</b></div>}
function StageGroups({items,edit}:{items:Project[];edit:(p:Project)=>void}){return <>{stages.map(stage=>{const list=items.filter(p=>stageOf(p.status)===stage);if(!list.length)return null;const color=colors[stage];return <section key={stage} className="mb-6 rounded-3xl border p-4" style={{borderColor:color+"55",background:color+"0d"}}><div className="mb-4 flex items-center gap-3"><i className="h-10 w-3 rounded-full" style={{background:color}}/><div><small className="text-sage">مرحلة العمل</small><h3 className="text-2xl font-black">{stage}</h3></div><span className="badge mr-auto" style={{color}}>{list.length} مشروع</span></div><div className="grid gap-4 xl:grid-cols-2">{list.map(p=><ProjectCard key={p.id} p={p} edit={()=>edit(p)} color={color}/>)}</div></section>})}</>}
function ProjectCard({p,edit,color}:{p:Project;edit:()=>void;color:string}){return <article className="card overflow-hidden" style={{borderTop:`5px solid ${color}`}}><div className="p-5"><div className="flex items-start justify-between gap-3"><div><small className="font-bold text-sage">{p.source_id||p.source}</small><h3 className="mt-1 text-xl font-black">{p.name}</h3></div><button onClick={edit} className="rounded-lg border border-ink/20 px-3 py-2 text-sm font-black">تعديل</button></div><div className="my-4 grid grid-cols-2 gap-2 text-sm"><Info label="موعد المشروع" value={p.deadline||"غير محدد"}/><Info label="الأولوية" value={p.priority}/><Info label="نسبة الإنجاز" value={`${p.progress}%`}/><Info label="المسؤول" value={p.assigned_to||"غير محدد"}/></div><div className="rounded-xl bg-paper p-4"><small className="font-black text-rust">التقرير اليومي</small><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{p.daily_report?.trim()||"لم يُكتب تقرير اليوم بعد."}</p></div></div></article>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-ink/10 p-3"><small className="block text-sage">{label}</small><b className="mt-1 block">{value}</b></div>}
function Editor({project,close,saved}:{project:Project|null;close:()=>void;saved:()=>void}){const initial=project||blank;const[busy,setBusy]=useState(false);const[err,setErr]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setErr("");const f=new FormData(e.currentTarget);const body={name:String(f.get("name")),client:String(f.get("client"))||null,description:String(f.get("description"))||null,daily_report:String(f.get("daily_report"))||null,status:String(f.get("status")),priority:String(f.get("priority")),start_date:String(f.get("start_date"))||null,deadline:String(f.get("deadline"))||null,progress:Number(f.get("progress")),assigned_to:String(f.get("assigned_to"))||null};try{await api(project?`/projects/${project.id}`:"/projects",{method:project?"PATCH":"POST",body:JSON.stringify(body)});saved()}catch(x){setErr(x instanceof Error?x.message:"تعذر الحفظ")}finally{setBusy(false)}}return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/55 p-4" dir="rtl" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form onSubmit={submit} className="card max-h-[92vh] w-full max-w-3xl overflow-y-auto p-6"><div className="mb-5 flex justify-between"><div><p className="text-xs font-black tracking-[.16em] text-sage">تعديل كل بيانات المشروع</p><h2 className="mt-1 text-2xl font-black">{project?project.name:"مشروع جديد"}</h2></div><button type="button" onClick={close} className="text-2xl">×</button></div><div className="grid gap-3 md:grid-cols-2"><Field name="name" label="اسم المشروع" value={initial.name} required/><Field name="client" label="العميل" value={initial.client||""}/><Select name="status" label="المرحلة" value={stageOf(initial.status)} options={stages}/><Select name="priority" label="الأولوية" value={initial.priority} options={["CRITICAL","HIGH","MEDIUM","LOW"]}/><Field name="start_date" label="تاريخ البداية" value={initial.start_date||""} type="date"/><Field name="deadline" label="موعد التسليم" value={initial.deadline||""} type="date"/><Field name="assigned_to" label="المسؤول" value={initial.assigned_to||""}/><Field name="progress" label="نسبة الإنجاز" value={String(initial.progress)} type="number" min="0" max="100"/></div><Text name="daily_report" label="التقرير اليومي" value={initial.daily_report||""} rows={5}/><Text name="description" label="ملاحظات ووصف المشروع" value={initial.description||""} rows={4}/>{err&&<p className="mt-3 rounded-xl bg-rust/10 p-3 font-bold text-rust">{err}</p>}<div className="mt-5 flex gap-3"><button disabled={busy} className="flex-1 rounded-xl bg-ink p-3 font-black text-white">{busy?"جاري الحفظ…":"حفظ التعديلات"}</button><button type="button" onClick={close} className="rounded-xl border border-ink px-5 font-bold">إلغاء</button></div></form></div>}
function Field({label,...p}:{label:string;name:string;value:string;type?:string;required?:boolean;min?:string;max?:string}){return <label className="text-sm font-bold">{label}<input {...p} className="mt-1 w-full rounded-xl border border-ink/20 p-3 font-normal"/></label>}
function Select({label,name,value,options}:{label:string;name:string;value:string;options:string[]}){return <label className="text-sm font-bold">{label}<select name={name} defaultValue={value} className="mt-1 w-full rounded-xl border border-ink/20 bg-white p-3 font-normal">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Text({label,name,value,rows}:{label:string;name:string;value:string;rows:number}){return <label className="mt-3 block text-sm font-bold">{label}<textarea name={name} defaultValue={value} rows={rows} className="mt-1 w-full rounded-xl border border-ink/20 p-3 font-normal"/></label>}
