import {env} from "cloudflare:workers";
const cors={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, content-type","access-control-allow-methods":"GET, POST, DELETE, OPTIONS"},ignoredProjects=new Set(["AA44474"]);
function summarize(value:string){const clean=value.replace(/https?:\/\/\S+/gi,"[رابط]").replace(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g,"[بريد]").replace(/(?:password|باسورد|كلمة المرور)\s*[:：=-]?\s*\S+/gi,"[بيانات محجوبة]").replace(/\s+/g," ").trim();return clean.length>180?`${clean.slice(0,177)}…`:clean}
function safeName(value?:string){const clean=(value||"").replace(/\s+/g," ").trim();return clean.slice(0,100)||"جروب مشروع"}
function classify(value:string){const link=/https?:\/\/\S+/i.test(value)||/\[رابط\]/.test(value);let category="رسالة مهمة",importance="متوسطة";if(/مستعجل|ضروري|عاجل|تأخير|متأخر|رفض|مشكلة|خطأ|شكوى|urgent|delay|late|reject|issue|bug|complaint/i.test(value)){category="مشكلة أو إجراء عاجل";importance="عالية"}else if(/تسليم|موعد|deadline|delivery/i.test(value)){category="موعد أو تسليم";importance="عالية"}else if(/تعديل|revision|change/i.test(value))category="تعديل";else if(/إضافة|اضافة|add|new feature/i.test(value))category="إضافة";else if(/ملاحظة|feedback|comment/i.test(value))category="ملاحظة";else if(/اعتماد|موافقة|approve/i.test(value))category="اعتماد";else if(/مطلوب|طلب|request/i.test(value))category="طلب";else if(link)category="رابط";return{category,importance}}
function isImportant(value:string){return /\[رابط\]|https?:\/\/\S+|تعديل|إضافة|اضافة|ملاحظة|مطلوب|طلب|اعتماد|موافقة|رفض|مشكلة|خطأ|تأخير|متأخر|مستعجل|ضروري|موعد|تسليم|اجتماع|انتظار|رد العميل|revision|change|add|approve|issue|bug|urgent|deadline|delivery|meeting|feedback|request/i.test(value)}
function isMyWhatsAppName(value?:string){return /awamer\s+alshabaka\s*1|أوامر\s+الشبكة\s*1/i.test(value||"")}
async function init(){const db=env.DB;await db.prepare(`CREATE TABLE IF NOT EXISTS whatsapp_updates (id INTEGER PRIMARY KEY AUTOINCREMENT, message_id TEXT NOT NULL UNIQUE, project_code TEXT NOT NULL, chat_name TEXT NOT NULL, sender TEXT, summary TEXT NOT NULL, message_date TEXT NOT NULL, created_at TEXT NOT NULL)`).run();await db.prepare(`CREATE INDEX IF NOT EXISTS idx_whatsapp_updates_date ON whatsapp_updates(message_date DESC)`).run();await db.prepare("DELETE FROM whatsapp_updates WHERE message_date < ?").bind(new Date(Date.now()-30*86400000).toISOString()).run()}
export async function OPTIONS(){return new Response(null,{status:204,headers:cors})}
export async function DELETE(request:Request){const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token||token!==env.WHATSAPP_INGEST_TOKEN)return Response.json({error:"Unauthorized"},{status:401,headers:cors});await init();const result=await env.DB.prepare("DELETE FROM whatsapp_updates").run();return Response.json({ok:true,deleted:result.meta.changes||0},{headers:cors})}
export async function GET(request:Request){await init();const url=new URL(request.url),period=url.searchParams.get("period")||"week",importantOnly=url.searchParams.get("important")==="1",days=period==="day"?1:period==="month"?30:7,cutoff=new Date(Date.now()-days*86400000).toISOString(),token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,""),rows=await env.DB.prepare("SELECT message_id AS messageId, project_code AS projectCode, chat_name AS chatName, sender, summary, message_date AS messageDate FROM whatsapp_updates WHERE message_date >= ? ORDER BY message_date DESC LIMIT 1000").bind(cutoff).all(),source=(rows.results as Array<{messageId:string;projectCode:string;chatName:string;sender:string;summary:string;messageDate:string}>).filter(row=>!ignoredProjects.has(row.projectCode.toUpperCase())),selected=importantOnly?source.filter(row=>row.sender!=="opened"&&isImportant(row.summary)):source,updates=selected.map(row=>({...row,...classify(row.summary),direction:row.sender,sender:token===env.WHATSAPP_INGEST_TOKEN?row.sender:null}));return Response.json({period,updates},{headers:{...cors,"cache-control":"no-store"}})}
export async function POST(request:Request){const token=request.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token||token!==env.WHATSAPP_INGEST_TOKEN)return Response.json({error:"Unauthorized"},{status:401,headers:cors});const body=await request.json() as {messageId?:string;projectCode?:string;chatName?:string;text?:string;messageDate?:string;direction?:"incoming"|"outgoing"|"opened";senderName?:string;authorName?:string;sender?:string};if(!body.messageId||!body.projectCode||!body.text)return Response.json({error:"Missing fields"},{status:400,headers:cors});if(ignoredProjects.has(body.projectCode.toUpperCase()))return Response.json({ok:true,ignored:true},{headers:cors});const identity=body.senderName||body.authorName||body.sender,direction=body.direction==="opened"?"opened":isMyWhatsAppName(identity)?"outgoing":body.direction||"incoming",summary=direction==="opened"?"تم فتح ومتابعة المحادثة.":summarize(body.text);if(!summary)return Response.json({error:"Empty message"},{status:400,headers:cors});await init();await env.DB.prepare("INSERT INTO whatsapp_updates (message_id,project_code,chat_name,sender,summary,message_date,created_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(message_id) DO UPDATE SET project_code=excluded.project_code,chat_name=excluded.chat_name,sender=excluded.sender,summary=excluded.summary,message_date=excluded.message_date").bind(body.messageId,body.projectCode,safeName(body.chatName),direction,summary,body.messageDate||new Date().toISOString(),new Date().toISOString()).run();return Response.json({ok:true,important:isImportant(body.text),direction,...classify(body.text)},{headers:cors})}
