"use client";
import {useEffect,useState} from "react";
import "./daily-plan.css";import "./daily-plan-extra.css";import "./notification-fallback.css";
import "./daily-plan-actions.css";
type Project={code:string;name:string;stage:string;plannedDay:string;expected:string|null;actual:string|null;weeklyProgressReminder?:boolean;progressPercent?:number|null;progressMessage?:string|null;progressBasis?:string|null;notes:Array<{date:string;text:string}>};type Activity={id:string;projectCode:string;projectName:string;source:"Odoo"|"WhatsApp";date:string;text:string;detail:string};type DayPlan={day:string;projects:Project[]};type Plan={date:string;today:string;isWorkday:boolean;planned:Project[];days:DayPlan[];workedOutsideToday:Activity[];weeklyDeliveries:Project[]};type AlertMode="off"|"system"|"inside"|"blocked";const workdays=["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس"];
export default function DailyPlanPanel(){const[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[toast,setToast]=useState(false),[selectedDay,setSelectedDay]=useState("");const[data,setData]=useState<Plan|null>(null),[mode,setMode]=useState<AlertMode>("off"),[message,setMessage]=useState("");
 async function load(){setLoading(true);try{const next=await fetch("/api/daily-plan",{cache:"no-store"}).then(r=>r.json()) as Plan;setData(next);setSelectedDay(current=>current||(next.isWorkday?next.today:"الأحد"));const inside=localStorage.getItem("dashboard-alerts")==="on",system=typeof Notification!=="undefined"&&Notification.permission==="granted";setMode(system?"system":inside?"inside":typeof Notification!=="undefined"&&Notification.permission==="denied"?"blocked":"off");if((inside||system)&&localStorage.getItem("daily-plan-notified")!==next.date){const body=`عليكِ ${next.planned.length} مشروع اليوم، و${next.weeklyDeliveries.length} تسليم مهم خلال 7 أيام.`;setMessage(body);setToast(true);if(system)try{new Notification(`مشاريع ${next.today}`,{body})}catch{}localStorage.setItem("daily-plan-notified",next.date)}}finally{setLoading(false)}}
 async function enable(){localStorage.setItem("dashboard-alerts","on");setMessage("تم تفعيل التنبيهات داخل الداشبورد على هذا الجهاز.");setToast(true);if(typeof Notification==="undefined"){setMode("inside");return}if(Notification.permission==="denied"){setMode("blocked");setMessage("تنبيهات النظام محظورة، لكن تنبيهات الداشبورد الداخلية اتفعلت.");return}try{const result=await Notification.requestPermission();if(result==="granted"){setMode("system");new Notification("تم تفعيل التنبيهات",{body:"ستصلك مهام اليوم والتسليمات المهمة على هذا الجهاز."})}else setMode(result==="denied"?"blocked":"inside")}catch{setMode("inside")}await load()}
 useEffect(()=>{load();const timer=setInterval(load,60000);return()=>clearInterval(timer)},[]);const shownDay=selectedDay||(data?.isWorkday?data.today:"الأحد"),shownProjects=data?.days.find(item=>item.day===shownDay)?.projects||[];
 return <>{toast&&<div className="dashboardToast"><button onClick={()=>setToast(false)}>×</button><b>تنبيه مهام اليوم</b><p>{message}</p></div>}<button className="dailyPlanLauncher" onClick={()=>setOpen(true)}><span>✓</span><b>مشاريع اليوم</b><small>{data?`${data.planned.length} مشروع اليوم · ${data.workedOutsideToday.length} خارج الخطة`:"الأحد إلى الخميس"}</small></button>{open&&<div className="planOverlay" onClick={()=>setOpen(false)}><section className="planDrawer" onClick={event=>event.stopPropagation()}><header><div><small>تقسيم أسبوعي متساوٍ · الأحد إلى الخميس</small><h2>مشاريع {shownDay}</h2></div><button onClick={()=>setOpen(false)}>×</button></header><div className="planActions"><button className={`notifyButton ${mode}`} onClick={enable}>{mode==="system"?"✓ التنبيهات مفعلة":mode==="inside"?"✓ تنبيهات الداشبورد مفعلة":"تفعيل التنبيهات"}</button></div>{mode==="blocked"&&<p className="notifyHelp">تنبيهات النظام محظورة، لكن الداخلية مفعلة.</p>}{loading&&!data&&<p className="planEmpty">جاري تحميل البيانات…</p>}{data&&<><div className="weekCounts">{workdays.map(day=>{const row=data.days.find(item=>item.day===day);return <button key={day} className={`${shownDay===day?"active":""} ${data.today===day?"today":""}`} onClick={()=>setSelectedDay(day)}><b>{day}</b><span>{row?.projects.length||0}</span>{data.today===day&&<small>اليوم</small>}</button>})}</div><h3 className="planTitle">مشاريع {shownDay} <span>{shownProjects.length}</span></h3><div className="planList">{shownProjects.map(p=><Card p={p} key={p.code}/>)}</div><h3 className="planTitle extra">اشتغلتِ عليه خارج خطة اليوم <span>{data.workedOutsideToday.length}</span></h3><div className="planList activityList">{data.workedOutsideToday.length?data.workedOutsideToday.map(item=><ActivityCard item={item} key={item.id}/>):<p className="planEmpty">لا يوجد عمل مسجل خارج خطة اليوم حتى الآن.</p>}</div><h3 className="planTitle delivery">تسليمات مهمة خلال 7 أيام <span>{data.weeklyDeliveries.length}</span></h3><div className="planList">{data.weeklyDeliveries.map(p=><Card p={p} key={p.code}/>)}</div></>}</section></div>}</>}
function ActivityCard({item}:{item:Activity}){return <article><div><small>{item.source} · {item.projectCode}</small><h4>{item.projectName}</h4></div><span className={`sourceBadge ${item.source.toLowerCase()}`}>{item.detail}</span><p>{item.text}</p><time>{new Date(item.date.replace(" ","T")+(/Z|[+-]\d\d:\d\d$/.test(item.date)?"":"Z")).toLocaleString("ar-EG",{dateStyle:"medium",timeStyle:"short"})}</time></article>}
function Card({p}:{p:Project}){return <article><div><small>{p.code} · {p.stage}</small><h4>{p.name}</h4></div>{p.weeklyProgressReminder&&<div className="progressReminder"><b>مهمة اليوم: إرسال النسبة الأسبوعية للعميل {p.progressPercent!==null&&p.progressPercent!==undefined?`(${p.progressPercent}%)`:""}</b>{p.progressBasis&&<small>{p.progressBasis}</small>}{p.progressMessage&&<p>{p.progressMessage}</p>}</div>}<div className="cardDates"><span>المتوقع: <b>{p.expected||"غير محدد"}</b></span><span>الفعلي: <b>{p.actual||"غير محدد"}</b></span></div>{p.notes[0]&&<p>{p.notes[0].text}</p>}</article>}

