import {projectDates} from "../../delivery-dates";
type Note={date:string;text:string};
type Project={code:string;name:string;stage:string;deadline:string|null;expectedDate?:string|null;actualDate?:string|null;designApprovalDate?:string|null;programmingDays?:number|null;notes:Note[]};
type WhatsAppUpdate={messageId:string;projectCode:string;chatName:string;summary:string;messageDate:string;category:string;importance:string;direction?:string};
type Activity={id:string;projectCode:string;projectName:string;source:"Odoo"|"WhatsApp";date:string;text:string;detail:string};
const dayNames=["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس"];
const fixedDays:Record<string,number>={"AA41581":0,"AA44819":0,"AA59015":0,"AA67663":0,"AA63106":0,"AA68357":1,"AA51142":1,"AA44546":1,"2091":1,"AA2091":1,"AA57068":1,"AA61569":1};
function cairoDate(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Cairo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),get=(type:string)=>parts.find(p=>p.type===type)?.value||"";return`${get("year")}-${get("month")}-${get("day")}`}
function codeKey(code:string){return code.toUpperCase().match(/AA\d+/)?.[0]||code.trim().toUpperCase()}
function workdaysElapsed(start:string,end:string){let count=0,cursor=new Date(`${start}T12:00:00Z`),last=new Date(`${end}T12:00:00Z`);cursor.setUTCDate(cursor.getUTCDate()+1);while(cursor<=last){const day=cursor.getUTCDay();if(day>=0&&day<=4)count++;cursor.setUTCDate(cursor.getUTCDate()+1)}return count}
function progressFor(project:Project,date:string){const programming=/برمج|programming|development/i.test(project.stage),start=project.designApprovalDate||null,total=project.programmingDays||null;if(!programming)return{weeklyProgressReminder:false,progressPercent:null,progressMessage:null,progressBasis:null};if(!start||!total)return{weeklyProgressReminder:true,progressPercent:null,progressMessage:"راجعي تاريخ اعتماد التصميم وعدد أيام البرمجة في الشيت قبل إرسال النسبة الأسبوعية.",progressBasis:"بيانات الحساب غير مكتملة"};const elapsed=workdaysElapsed(start,date),percent=Math.min(100,Math.max(0,Math.round(elapsed/total*100))),message=`السلام عليكم، نشارككم التحديث الأسبوعي لمشروع ${project.name}: النسبة الزمنية المتوقعة حتى اليوم ${percent}%، وجارٍ متابعة التنفيذ وفق الخطة المعتمدة.`;return{weeklyProgressReminder:true,progressPercent:percent,progressMessage:message,progressBasis:`اعتماد التصميم ${start} · ${elapsed} من ${total} يوم عمل برمجي`}}
function decorate(project:Project,plannedDayIndex:number,date:string){const fallback=projectDates(project.code),expected=project.expectedDate??fallback.expected,actual=project.actualDate??fallback.actual;return{...project,expected,actual,plannedDayIndex,plannedDay:dayNames[plannedDayIndex],...progressFor(project,date)}}
function urgency(p:Project){let score=p.notes.length*10;if(p.deadline)score+=Math.max(0,100-Math.floor((new Date(p.deadline).getTime()-Date.now())/86400000));if(/اختبار|testing|تسليم|delivery/i.test(p.stage))score+=5;return score}
export async function GET(request:Request){
 const origin=new URL(request.url).origin,[odooResponse,waResponse]=await Promise.all([fetch(`${origin}/api/odoo?period=month`,{cache:"no-store"}),fetch(`${origin}/api/whatsapp?period=month`,{cache:"no-store"})]);
 if(!odooResponse.ok)return Response.json({error:"Unable to build daily plan"},{status:502});
 const data=await odooResponse.json() as{projects:Project[];syncedAt:string},waData=waResponse.ok?await waResponse.json() as{updates?:WhatsAppUpdate[]}:{updates:[]},whatsapp=(waData.updates||[]).filter(item=>item.direction!=="opened"),date=cairoDate(),todayIndex=new Date(`${date}T12:00:00Z`).getUTCDay();
 const waPriority=new Map<string,number>();for(const item of whatsapp){const age=Math.max(0,30-Math.floor((Date.now()-new Date(item.messageDate).getTime())/86400000)),importance=item.importance==="عالية"?35:15,action=/تعديل|مشكلة|تسليم|موعد|ملاحظة|طلب|اعتماد/i.test(item.category+" "+item.summary)?20:0,key=codeKey(item.projectCode);waPriority.set(key,(waPriority.get(key)||0)+age+importance+action)}const priority=(project:Project)=>urgency(project)+(waPriority.get(codeKey(project.code))||0),fixed=data.projects.filter(project=>fixedDays[codeKey(project.code)]!==undefined),remaining=data.projects.filter(project=>fixedDays[codeKey(project.code)]===undefined).sort((a,b)=>priority(b)-priority(a)),assigned=[...fixed.map(project=>decorate(project,fixedDays[codeKey(project.code)],date)),...remaining.map((project,index)=>decorate(project,index===0?0:index<=6?2:index<=13?3:4,date))],days=dayNames.map((day,index)=>({day,projects:assigned.filter(p=>p.plannedDayIndex===index).sort((a,b)=>priority(b)-priority(a))})),planned=todayIndex<=4?days[todayIndex].projects:[],plannedCodes=new Set(planned.map(p=>codeKey(p.code))),projectMap=new Map(assigned.map(p=>[codeKey(p.code),p]));
 const odooActivities:Activity[]=data.projects.flatMap(project=>project.notes.map((note,index)=>({id:`odoo-${codeKey(project.code)}-${note.date}-${index}`,projectCode:project.code,projectName:project.name,source:"Odoo" as const,date:note.date,text:note.text,detail:"Log Note"})));
 const whatsappActivities:Activity[]=whatsapp.map(item=>({id:`wa-${item.messageId}`,projectCode:item.projectCode,projectName:projectMap.get(codeKey(item.projectCode))?.name||item.chatName,source:"WhatsApp" as const,date:item.messageDate,text:item.summary,detail:`${item.category||"رسالة"} · أهمية ${item.importance||"متوسطة"}`}));
 const updates=[...odooActivities,...whatsappActivities].sort((a,b)=>b.date.localeCompare(a.date));
 const workedOutsideToday=[...odooActivities.filter(item=>item.date.slice(0,10)===date&&!plannedCodes.has(codeKey(item.projectCode))),...whatsappActivities.filter(item=>item.date.slice(0,10)===date&&whatsapp.find(row=>`wa-${row.messageId}`===item.id)?.direction==="outgoing"&&!plannedCodes.has(codeKey(item.projectCode)))].sort((a,b)=>b.date.localeCompare(a.date));
 const counts=days.map(item=>({day:item.day,count:item.projects.length})),start=new Date(`${date}T00:00:00Z`).getTime(),end=start+7*86400000,weeklyDeliveries=assigned.filter(p=>{const target=p.actual||p.expected;if(!target)return false;const time=new Date(`${target}T00:00:00Z`).getTime();return time>=start&&time<end}).sort((a,b)=>(a.actual||a.expected||"").localeCompare(b.actual||b.expected||""));
 return Response.json({date,today:todayIndex<=4?dayNames[todayIndex]:todayIndex===5?"الجمعة":"السبت",isWorkday:todayIndex<=4,planned,days,workedOutsideToday,updates,weeklyDeliveries,weeklyProgressCount:planned.filter(p=>p.weeklyProgressReminder).length,counts,total:assigned.length,syncedAt:data.syncedAt},{headers:{"cache-control":"no-store"}})
}
