import {loadLiveSheetProjects} from "../../google-sheet-live";

type RpcResult={result?:unknown;error?:{message?:string;data?:{message?:string}}};
let requestId=0;
function clean(text:string){return text.replace(/<a\b[^>]*>[\s\S]*?<\/a>/gi," ").replace(/https?:\/\/\S+/gi," ").replace(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g," ").replace(/(?:password|كلمة المرور|باسورد)\s*[:：=-]?\s*\S+/gi,"[بيانات محجوبة]").replace(/<br\s*\/?\s*>/gi,"\n").replace(/<[^>]+>/g," ").replace(/&nbsp;|&#160;/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/[ \t]+/g," ").replace(/\n\s*\n+/g,"\n").trim()}
function summarize(body:string){const hasLink=/<a\b|https?:\/\//i.test(body);const text=clean(body);if(!text)return"";const approved=/تم\s+(?:ال)?اعتماد|اعتمد\s+العميل|تمت\s+الموافقة/.test(text);if(/محضر\s+(?:ال)?اجتماع/i.test(text)){const minutesApproved=/تم\s+(?:ال)?اعتماد\s+محضر|محضر.{0,20}(?:معتمد|تمت\s+الموافقة)/.test(text);return minutesApproved?"تم اعتماد محضر الاجتماع.":"تم إضافة محضر الاجتماع."}if(hasLink){let subject=/docs\.google\.com\/spreadsheets/i.test(body)?"شيت المتابعة":/docs\.google\.com\/document/i.test(body)?"مستند Google Docs":/drive\.google\.com/i.test(body)?"ملف Google Drive":"الرابط المرفق";if(/تحليل/.test(text))subject="ملف التحليل";else if(/تصميم|واجهات/.test(text))subject="ملف التصميم";else if(/اجتماع/.test(text))subject="رابط الاجتماع";else if(/موقع|ويب/.test(text))subject="رابط الموقع";else if(/تطبيق/.test(text))subject="رابط التطبيق";else if(/عرض فني|متطلبات/.test(text))subject="ملف المتطلبات";return approved?`تم اعتماد ${subject}.`:`تم إرفاق ${subject}.`}const last=text.match(/آخر ملاحظات الحالة\s*:\s*([^\n]+)/)?.[1]?.trim();if(last)return last.length>140?`${last.slice(0,137)}…`:last;if(text.length<=140)return text;if(/تعديل|ملاحظات|اعتراض/.test(text))return"تم تسجيل تعديلات وملاحظات العميل.";if(/نطاق المشروع|المتطلبات|خدمات مطلوبة/.test(text))return"تم تسجيل متطلبات المشروع.";return`${text.slice(0,137)}…`}
function projectCode(name:string,id:number){const exact=name.match(/AA\d+/i)?.[0];if(exact)return exact.toUpperCase();const singleA=name.match(/(?:^|\W)A(\d{5,})/i)?.[1];if(singleA)return`AA${singleA}`;const trailing=name.match(/(?:-|\s)(\d{4})\s*$/)?.[1];if(trailing)return name.includes("AA")?`AA${trailing}`:trailing;return name.match(/^S\d+/i)?.[0].toUpperCase()||String(id)}
export async function GET(request:Request){
  const url=new URL(request.url);const period=url.searchParams.get("period")||"week";const days=period==="day"?1:period==="month"?30:7;const cutoff=new Date(Date.now()-days*86400000).toISOString().slice(0,19).replace("T"," ");
  const base=(process.env.ODOO_URL||"").replace(/\/$/,"");const db=process.env.ODOO_DATABASE||"";const login=process.env.ODOO_USERNAME||"";const password=process.env.ODOO_PASSWORD||"";
  if(!base||!db||!login||!password)return Response.json({error:"Odoo sync is not configured"},{status:503});
  let cookie="";
  async function rpc(path:string,params:Record<string,unknown>){const response=await fetch(base+path,{method:"POST",headers:{"content-type":"application/json",...(cookie?{cookie}: {})},body:JSON.stringify({jsonrpc:"2.0",method:"call",params,id:++requestId})});const setCookie=response.headers.get("set-cookie");if(setCookie)cookie=setCookie.split(";")[0];if(!response.ok)throw new Error(`Odoo HTTP ${response.status}`);const body=await response.json() as RpcResult;if(body.error)throw new Error(body.error.data?.message||body.error.message||"Odoo error");return body.result}
  try{
    const session=await rpc("/web/session/authenticate",{db,login,password}) as {uid?:number};if(!session?.uid)throw new Error("Odoo authentication failed");
    const call=(model:string,method:string,args:unknown[],kwargs:Record<string,unknown>)=>rpc("/web/dataset/call_kw",{model,method,args,kwargs});
    const sheetMap=await loadLiveSheetProjects().catch(()=>new Map());
    const domain=sheetMap.size?[]:[["user_id","=",session.uid]];
    const rawProjects=await call("project.project","search_read",[domain],{fields:["id","name","date","stage_id","write_date"],context:{active_test:false},limit:1000}) as Array<{id:number;name:string;date:string|false;stage_id:[number,string]|false;write_date:string}>;
    const projects=rawProjects.filter(project=>{const code=projectCode(project.name,project.id);return code!=="AA44474"&&(!sheetMap.size||sheetMap.has(code))});
    const ids=projects.map(p=>p.id);const messages=ids.length?await call("mail.message","search_read",[[["model","=","project.project"],["res_id","in",ids],["subtype_id","=",2],["date",">=",cutoff]]],{fields:["id","res_id","date","body","author_id"],order:"date desc",limit:2000}):[] as unknown[];
    const notes=new Map<number,Array<{date:string;text:string}>>();for(const m of messages as Array<{res_id:number;date:string;body:string;author_id:[number,string]|false}>){if(!m.author_id||!m.author_id[1].includes("نهال"))continue;const text=summarize(m.body||"");if(!text)continue;const list=notes.get(m.res_id)||[];list.push({date:m.date,text});notes.set(m.res_id,list)}
    return Response.json({syncedAt:new Date().toISOString(),period,cutoff,projects:projects.map(p=>{const code=projectCode(p.name,p.id),sheet=sheetMap.get(code),odooNotes=notes.get(p.id)||[];return{id:p.id,code,name:sheet?.name||p.name,stage:sheet?.stage||(p.stage_id?p.stage_id[1]:"Technical Support"),deadline:sheet?.expectedDate||p.date||null,expectedDate:sheet?.expectedDate||null,actualDate:sheet?.actualDate||null,designApprovalDate:sheet?.designApprovalDate||null,programmingDays:sheet?.programmingDays||null,updatedAt:p.write_date,notes:odooNotes.length?odooNotes:sheet?.note?[{date:"آخر تحديث مباشر من الشيت",text:sheet.note}]:[]}})},{headers:{"cache-control":"no-store, no-cache, must-revalidate"}});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to sync Odoo"},{status:502})}
}
