(()=>{
  if(window.__NWS)return; window.__NWS=1;
  let chat=""; const seen=new Set();
  function valid(value){const v=(value||"").replace(/\s+/g," ").trim();if(!v||/^(online|متصل|يكتب|typing|last seen|آخر ظهور)/i.test(v))return"";const digits=(v.match(/\d/g)||[]).length;return /^[+\d\s(),،.-]+$/.test(v)||digits>Math.max(5,v.length*.45)?"":v}
  function name(){const direct=document.querySelector("#main header [data-testid='conversation-info-header-chat-title']");let value=valid(direct?.getAttribute("title")||direct?.textContent);if(value)return value;for(const selector of["#main header [role='button'] span[dir='auto']","#main header span[dir='auto'][title]","#main header span[title]"])for(const element of document.querySelectorAll(selector)){value=valid(element.getAttribute("title")||element.textContent);if(value)return value}return""}
  const rows=()=>[...document.querySelectorAll("#main [data-testid='msg-container'],#main .message-in,#main .message-out,#main [data-id]")];
  const messageText=element=>[...element.querySelectorAll("span.selectable-text,[data-testid='msg-text']")].map(node=>node.textContent?.trim()).filter(Boolean).join(" ");
  function sentAt(element){const box=element.closest("[data-pre-plain-text]")||element.querySelector("[data-pre-plain-text]"),raw=box?.getAttribute("data-pre-plain-text")||"",match=raw.match(/\[(\d{1,2}):(\d{2})(?:\s*(AM|PM|ص|م))?[,،]\s*(\d{1,2})[\/.](\d{1,2})[\/.](\d{2,4})\]/i);if(match){let hour=+match[1],year=+match[6];if(year<100)year+=2000;if(/PM|م/i.test(match[3]||"")&&hour<12)hour+=12;if(/AM|ص/i.test(match[3]||"")&&hour===12)hour=0;const date=new Date(year,+match[5]-1,+match[4],hour,+match[2]);if(!isNaN(date.getTime()))return date.toISOString()}const datetime=element.querySelector("time[datetime]")?.getAttribute("datetime");return datetime&&!isNaN(Date.parse(datetime))?new Date(datetime).toISOString():new Date().toISOString()}
  function authorName(element){const box=element.closest("[data-pre-plain-text]")||element.querySelector("[data-pre-plain-text]"),raw=box?.getAttribute("data-pre-plain-text")||"",match=raw.match(/\]\s*([^:]{1,80}):\s*$/);return(match?.[1]||"").trim()}
  async function send(body){try{const response=await fetch(NEHAL_SYNC_CONFIG.endpoint,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${NEHAL_SYNC_CONFIG.token}`},body:JSON.stringify(body)});if(response.ok){const state=await chrome.storage.local.get("sentCount");chrome.storage.local.set({sentCount:(state.sentCount||0)+1,lastSentAt:new Date().toISOString()})}}catch{}}
  function hash(value){let h=0;for(let i=0;i<value.length;i++)h=(h*31+value.charCodeAt(i))|0;return Math.abs(h).toString(36)}
  async function one(element,code,chatName){const text=messageText(element);if(!text)return;const bubble=element.closest(".message-in,.message-out"),box=bubble||element.closest("[data-id]")||element,id=box.getAttribute("data-id")||element.closest("[data-id]")?.getAttribute("data-id")||`visible_${code}_${hash(text)}`,author=authorName(element),mine=/Awamer\s*ALshabaka\s*1/i.test(author),direction=mine||bubble?.classList.contains("message-out")||/(^|_)true_/.test(id)?"outgoing":bubble?.classList.contains("message-in")||/(^|_)false_/.test(id)?"incoming":"incoming";if(seen.has(id))return;seen.add(id);await send({messageId:id,projectCode:code,chatName,authorName:author,senderName:author,text,direction,messageDate:sentAt(element)})}
  async function scan(){const chatName=name();if(!chatName)return;const{mappings={}}=await chrome.storage.local.get("mappings"),code=mappings[chatName];if(chatName!==chat){chat=chatName;if(code){const day=new Date().toISOString().slice(0,10);await send({messageId:`opened_${day}_${code}`,projectCode:code,chatName,text:"opened",direction:"opened",messageDate:new Date().toISOString()});for(const element of rows().slice(-60))await one(element,code,chatName)}return}if(code)for(const element of rows())await one(element,code,chatName)}
  setInterval(scan,1400);
  chrome.runtime.onMessage.addListener((message,sender,respond)=>{if(message.type==="CURRENT_CHAT")respond({chatName:name()});if(message.type==="MAPPING_SAVED"){chat="";respond({ok:true})}return true});
})();
